parameters:
  platforms: { Linux: ubuntu-latest, Windows: vs2017-win2016 }
  testRunTypes: ['Unit', 'Integration']
  installationType:
  pyVersions: [3.6, 3.7, 3.8]
  freezeArtifactStem: 
  freezeFileStem:
  # Following are used if the installationType is PyPI
  targetType: 'Test'
  versionArtifactName:
  versionArtifactFile:
  # Following used if installationType is WheelArtifact
  wheelArtifactName:

jobs:
  - ${{ each plat in parameters.platforms }}:
    - ${{ each testRunType in parameters.testRunTypes }}:
      - ${{ each pyVer in parameters.pyVersions }}:
        - job:
          displayName: ${{ format('{0} {1} {2}', plat.Key , testRunType, pyVer) }}
          pool:
            vmImage: ${{ plat.value }}

          variables:
            ${{ if eq(parameters.targetType, 'Test') }}:
              pypiUrl: https://test.pypi.org/simple/
            ${{ if eq(parameters.targetType, 'Production') }}:
              pypiUrl: https://pypi.org/simple/
            FreezeArtifact: '${{parameters.freezeArtifactStem}}-${{plat.Key}}-${{testRunType}}-${{pyVer}}'
            FreezeFile: '${{parameters.freezeFileStem}}-${{plat.Key}}-${{testRunType}}-${{pyVer}}.txt'

          
          steps:
          - template: test-run-step-template.yml
            parameters:
              testRunType: ${{testRunType}}
              installationType: ${{parameters.installationType}}
              pythonVersion: ${{pyVer}}
              freezeArtifact: $(FreezeArtifact)
              freezeFile: $(FreezeFile)
              # Following are used if the installationType is PyPI
              pypiUrl: $(pypiUrl)
              versionArtifactName: ${{parameters.versionArtifactName}}
              versionArtifactFile: ${{parameters.versionArtifactFile}}
              # Following used if installationType is WheelArtifact
              wheelArtifactName: ${{parameters.wheelArtifactName}}