# See:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/anaconda?view=azure-devops&tabs=macos#add-conda-to-your-system-path


parameters:
- name: AgentOS
  type: string
  values:
 # - Windows_NT
 # - Darwin
 # - Linux

steps:
- bash: echo ${{parameters.AgentOS}}
  displayName: Show OS for conda path
  

- ${{ if eq(parameters.AgentOS, 'Windows_NT')}}:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

- ${{ if eq(parameters.AgentOS, 'Darwin')}}:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  # On Hosted macOS, the agent user doesn't have ownership of Miniconda's installation directory/
  # We need to take ownership if we want to update conda or install packages globally
  - bash: sudo chown -R $USER $CONDA
    displayName: Take ownership of conda installation

- ${{ if eq(parameters.AgentOS, 'Linux')}}:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH