# Nightly build pipeline

variables:
  EnvArtifactStem: 'environment'
  EnvFileStem: 'environment'

trigger: none # No CI build

pr: none # Not for pull requests

schedules:
- cron: "0 7 * * *" # Time is UTC
  displayName: Nightly Build
  branches:
    include:
      - master
  always: true

pool:
  vmImage: 'ubuntu-latest'

  
jobs:
- template: templates/all-tests-job-template.yml
  parameters:
    platforms:  { Linux: ubuntu-latest }
    pyVersions: [3.6.8]
    envArtifactStem: $(EnvArtifactStem)
    envFileStem: $(EnvFileStem)

- template: templates/all-tests-job-template.yml
  parameters:
    platforms:  { Windows: vs2017-win2016 }
    pyVersions: [3.6.8]
    envArtifactStem: $(EnvArtifactStem)
    envFileStem: $(EnvFileStem)

- template: templates/all-tests-job-template.yml
  parameters:
    platforms:  { MacOS: macos-latest}
    pyVersions: [3.6.8]
    envArtifactStem: $(EnvArtifactStem)
    envFileStem: $(EnvFileStem) 